DROP TABLE IF EXISTS T_STUDENT;

CREATE TABLE T_STUDENT (
  REGISTRATION_NUMBER INT PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  EMAIL VARCHAR(250) NOT NULL,
  YEAR_OF_REGISTRATION VARCHAR(250) DEFAULT NULL,
  SECTION VARCHAR(250) NOT NULL,
  ADDRESS_ID INT
);

DROP TABLE IF EXISTS T_ADDRESS;

CREATE TABLE T_ADDRESS (
  ADDRESS_ID INT PRIMARY KEY,
  ADDRESS_1 VARCHAR(250) NOT NULL,
  STREET VARCHAR(250) NOT NULL,
  STATE VARCHAR(250) DEFAULT NULL
);